### PR TITLE
Ward fix

### PR DESCRIPTION
**Pull request by noobling**
vision ward is currently not being detected this fixes that

### CODE REVIEW

**Comment by Hellsing** [comment]
Are you sure that the BuffName is jammer device aswell?

**Comment by Hellsing** [comment]
Also, is the VisionWard completely removed?

**Comment by noobling** [comment]
Yes i am sure buffname changed but you can just test it out yourself to double check. 

"Visionward completely removed" not sure what you mean. Only things that have changed is the name of visionward now called jammer device.

**Comment by Hellsing** [comment]
If that's the case then you should rename the class from VisionWard to JammerDevice and also remove the VIsionWard entry in the ward type enum, then I'll merge it.

**Comment by Hellsing** [comment]
Also, please make sure that everything compiles and works ingame after those changes.

**Comment by Hellsing** [comment]
Well, according to this page it's name is "Control Ward" now, please name the class and enum type like this instead.

http://leagueoflegends.wikia.com/wiki/Control_Ward

**Comment by noobling** [comment]
I believe the enum type has to jammerdevice I can't remember the exact reason. But the file names I can change to "ControlWard" if you like.

**Comment by Hellsing** [comment]
If you want this PR to get accepted you should rename the class to ControlWard.cs and remove the VisionWard entry in the ward type enum and fix the compiling issues due to that.

**Comment by noobling** [comment]
Yea i can do that. 

Why do you just want the class renamed? why not just rename every instance of visionward to controlward?

**Comment by Hellsing** [comment]
Renaming the class from VisionWard to ControlWard requires everything to be changed in order to have no compiling errors. I thought you would figure on your own that you need to do that aswell...

**Comment by noobling** [comment]
Ok, btw if you are wondering why I cannot use controlward for enum type it is because of this code `Enum.TryParse(obj.BaseSkinName, out wardType)`

**Comment by Hellsing** [comment]
Well in that case there is no need for the
`JammerDevice = 1,`
either. Since you added it but never used it.

**Comment by noobling** [comment]
? 
you need `JammerDevice = 1` because of `Enum.TryParse(obj.BaseSkinName, out wardType)`
since `obj.BaseSkinName` has a possibility of containing `JammerDevice`

**Comment by Hellsing** [comment]
What about regular VisionWard then? Since you changed the detection code in the VisionWard.cs file to contain only JammerDevice related info.

**Pull request closed without merging**
